Fix required form radio/checkbox fields
godaddy-wordpress/coblocks pull request #1643
Opened 2020-08-25 00:02 UTC by EvanHerman

### Description
Made sure that the checkboxes/radio fields of form block, when set to required, prevent the form from being submitted until at least one option/checkbox is selected.

**Note:** HTML does not provide a way to require checkbox groups. The workaround was to enqueue a script and display a notice above the field when no checkboxes were checked.

**The notice:** `Please check one of these options.`
**Wrapped in the filter:** `coblocks_form_checkbox_required_text`

### Screenshots
![form-checkboxes](https://user-images.githubusercontent.com/5321364/91107893-6c751b00-e644-11ea-9223-e05dc1dcbf77.gif)

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Manually

### Checklist:
- [ ] My code is tested
- [x] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2020-08-31 20:10 UTC, AnthonyLedesma commented on includes/class-coblocks-form.php
> +				(string) apply_filters( 'coblocks_form_checkbox_required_text', esc_html__( 'Please select at least one checkbox.', 'coblocks' ) )
If we are adding a new filter then we should also update the Docs to include information on this filter and how to apply it.

2020-08-31 20:10 UTC, AnthonyLedesma commented on src/js/coblocks-checkbox-required.js
> +} );
Ideally, we should avoid using jQuery in a case like this. `show`, `hide`, and `find` can all be replicated with vanilla javascript without needing to load jQuery.

2020-08-31 20:13 UTC, AnthonyLedesma commented on includes/class-coblocks-form.php
> +				array( 'jquery' ),
I left another comment regarding keeping jQuery as a dependency here. In the interest of continuing to work toward https://github.com/godaddy-wordpress/coblocks/issues/1365, we should ideally avoid the use of jQuery all together.

2020-08-31 20:15 UTC, AnthonyLedesma commented on .dev/tests/phpunit/includes/test-coblocks-form.php
> +		$this->assertArrayHasKey( 'coblocks-datepicker', $wp_scripts->registered );
Should be `'coblocks-checkbox-required'` not `'coblocks-datepicker'`

2020-09-02 17:39 UTC, EvanHerman commented
@AnthonyLedesma Good for another review 👌

2020-09-03 17:10 UTC, AnthonyLedesma commented
Confirmed this closes #1653.

2020-09-03 17:15 UTC, AnthonyLedesma requested changes
We are very close. The required attributes seem to be properly preventing form submission but we have a case where no errors are shown to the user. To replicate this bug use the following markup. 
```
<!-- wp:coblocks/form -->
<!-- wp:coblocks/field-email {"required":true} /-->

<!-- wp:coblocks/field-radio {"required":true,"options":["Yes","No"]} /-->

<!-- wp:coblocks/field-checkbox {"required":true,"options":["Yes","No"]} /-->

<!-- wp:coblocks/field-textarea {"required":true} /-->

<!-- wp:coblocks/field-submit-button {"submitButtonText":"Contact Us"} /-->
<!-- /wp:coblocks/form -->
```

When you leave the radio options unchecked and fill all other form elements, we have a case where form fails to submit and no errors are shown to the user. There should be an error message here specifying that an option must be selected.

2020-09-03 19:34 UTC, EvanHerman commented
@AnthonyLedesma This was a bug with Go, setting the radio buttons to `appearance: none;`

Feel free to pull down https://github.com/godaddy-wordpress/go/pull/579 and test, or use a different theme.

2020-09-03 19:51 UTC, AnthonyLedesma approved these changes
Confirmed that the bug reported was with Go.

2020-09-03 19:51 UTC, merged