WPEX-1486 Implement MediaReplaceFlow component for Service Item block
godaddy-wordpress/coblocks pull request #2030
Opened 2021-09-16 01:00 UTC by snovosel

### Description

This PR implements the Replace flow that is available from core using the MediaReplaceFlow component on the Service Item block toolbar

### Screenshots

<img width="1157" alt="Screen Shot 2021-09-15 at 8 59 32 PM" src="https://user-images.githubusercontent.com/18115694/133532474-b2f12b64-a0e8-46e8-ba08-c54c0bff689e.png">

### Types of changes

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-09-21 16:28 UTC, AnthonyLedesma requested changes
Functionality-wise things working great however I am getting this in Chrome. Do you mind fixing these styles first?

![image](https://user-images.githubusercontent.com/30462574/134209379-da22e167-0ef0-4207-af95-e7a507e8bbb4.png)

Check out how we do the styles in the gallery blocks. I believe we need to drop the box-shadow and use a border but I am not positive on the specifics.

![image](https://user-images.githubusercontent.com/30462574/134209765-b9bd1b4e-7df0-47c6-9cc5-ad6401b60aad.png)

2021-09-21 16:30 UTC, AnthonyLedesma commented
BTW you are safe to ignore this JS test error in CI. This is because you are not up to date with master.

2021-09-22 14:22 UTC, AnthonyLedesma approved these changes
LGTM

2021-09-27 21:54 UTC, jrtashjian approved these changes

2021-09-27 21:55 UTC, merged