WPEX-1487 remove example from Gallery Carousel block
godaddy-wordpress/coblocks pull request #2049
Opened 2021-09-29 19:34 UTC by snovosel

### Description

This PR removes the example preview for the gallery carousel block within the menu inserter. 

Due to a core bug here - https://github.com/WordPress/gutenberg/issues/35229 the block preview is not able to be used. We are waiting to hear how the core team will handle the bug before merging this PR.

### Screenshots

### Types of changes

Bug Fix

### How has this been tested?

Visually

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-09-30 22:01 UTC, AnthonyLedesma requested changes

2021-09-30 22:01 UTC, AnthonyLedesma commented on src/blocks/gallery-carousel/index.js
> -	},
So I was thinking about this and how we are now going and adding examples back where we did not have them. Here we are removing the example and the reason is made clear within this PR but I think the reason initially looking at the code is not clear. For that reason, I would suggest adding an additional comment here specifying the reason that no example is present. Something like:


```
	attributes,
	variations,
	icon: <Icon icon={ icon } />,
	keywords: [...],
	// Diable reason: link to the issue in GB
        // example,
```

2021-11-19 19:10 UTC, olafleur-godaddy commented
Reopening as it appears that in WP 5.9 (at least the nightly current version), not only the Gallery Carousel block preview generate a console error message, but it also make the editor explode.

2021-11-19 19:15 UTC, olafleur-godaddy approved these changes

2021-11-19 19:27 UTC, merged