Check for WP_Error in wp_remote_get; fixes #2386
godaddy-wordpress/coblocks pull request #2387
Opened 2022-05-23 18:31 UTC by thefrosty

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Acceptance criteria

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-05-25 14:35 UTC, olafleur-godaddy commented
The pipeline does not seem to run our your PR (maybe a config issue), but I can see that the PHP tests and linting are failing (ex : https://app.circleci.com/pipelines/github/godaddy-wordpress/coblocks/9503/workflows/1e53351b-47d1-4a51-812f-4e7d3f87773f ) 

Please make sure that the `yarn lint:php` and `yarn test:php` commands are not failing.

Thank you!

2022-05-25 14:35 UTC, olafleur-godaddy commented
The pipeline does not seem to run our your PR (maybe a config issue), but I can see that the PHP tests and linting are failing (ex : https://app.circleci.com/pipelines/github/godaddy-wordpress/coblocks/9503/workflows/1e53351b-47d1-4a51-812f-4e7d3f87773f ) 

Please make sure that the `yarn lint:php` and `yarn test:php` commands are not failing.

Thank you!

2022-05-26 15:01 UTC, olafleur-godaddy requested changes
The pipeline does not seem to run our your PR (maybe a config issue), but I can see that the PHP tests and linting are failing (ex : https://app.circleci.com/pipelines/github/godaddy-wordpress/coblocks/9503/workflows/1e53351b-47d1-4a51-812f-4e7d3f87773f )

Please make sure that the `yarn lint:php` and `yarn test:php` commands are not failing.

Thank you!

2022-05-31 18:12 UTC, thefrosty commented on src/blocks/gist/index.php
> +	if ( !is_array( $result ) || empty( $result['files'] ) || is_wp_error( $result ) {
```suggestion
	if ( ! is_array( $result ) || empty( $result['files'] ) || is_wp_error( $result ) ) {
```

2022-06-08 16:13 UTC, AnthonyLedesma approved these changes
Excellent change here. We appreciate the effort to get this PR in and fixed up.

2022-06-08 16:13 UTC, merged

2022-06-08 16:17 UTC, olafleur-godaddy commented
Yes, thanks for your contribution!

2022-06-08 16:20 UTC, olafleur-godaddy commented
I just added you in the contributors list : https://github.com/godaddy-wordpress/coblocks/blob/master/CONTRIBUTORS.md